version: '3.1'

services:

  postgres:
    image: postgres:alpine3.17
    container_name: todolist-db
    restart: always
    environment:
      POSTGRES_DB: todolist-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'